// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBu_WvqyQ-JOj6Q-tAcs1i_pZY7E6cNYE',
    appId: '1:75617116863:web:f346b70f7c91b091fe1c0a',
    messagingSenderId: '75617116863',
    projectId: 'kuet-bus',
    authDomain: 'kuet-bus.firebaseapp.com',
    storageBucket: 'kuet-bus.firebasestorage.app',
    measurementId: 'G-CY1801QY59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCYdNrr8IJ0MYW5Uav49ZLS-86zoU5Hb4',
    appId: '1:75617116863:android:a5e912b8a1a4eaaefe1c0a',
    messagingSenderId: '75617116863',
    projectId: 'kuet-bus',
    storageBucket: 'kuet-bus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8kX133PdOFJrvDLfg7zOLr15G3HZeJEE',
    appId: '1:75617116863:ios:f0d7c540bb8417a6fe1c0a',
    messagingSenderId: '75617116863',
    projectId: 'kuet-bus',
    storageBucket: 'kuet-bus.firebasestorage.app',
    iosBundleId: 'com.example.kuetBus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8kX133PdOFJrvDLfg7zOLr15G3HZeJEE',
    appId: '1:75617116863:ios:f0d7c540bb8417a6fe1c0a',
    messagingSenderId: '75617116863',
    projectId: 'kuet-bus',
    storageBucket: 'kuet-bus.firebasestorage.app',
    iosBundleId: 'com.example.kuetBus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBu_WvqyQ-JOj6Q-tAcs1i_pZY7E6cNYE',
    appId: '1:75617116863:web:e93c59c542d6e837fe1c0a',
    messagingSenderId: '75617116863',
    projectId: 'kuet-bus',
    authDomain: 'kuet-bus.firebaseapp.com',
    storageBucket: 'kuet-bus.firebasestorage.app',
    measurementId: 'G-XH5CH1JDX5',
  );
}
